name: Production release

on:
  create:
    tags:
      - "release-*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup release
       run: |
          echo "release done"