name: Production release workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Create release tag
    types:
      - completed
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup release
        run: |
          echo "release done"
