name: Production release released

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup release
        run: |
          echo "release done $GITHUB_REF"